on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - '*.md'
  pull_request_target:
  workflow_dispatch:

name: CI

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.0'
          - '3.1'
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake
